'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class angkagiliran_create

    '''<summary>
    '''ddlTahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTahun As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkSesi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSesi As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlKodKursus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKodKursus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlNamaKelas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNamaKelas As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCari As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divMsgResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMsgResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMsgResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''datRespondent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datRespondent As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnAngkagiliran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAngkagiliran As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKolejID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKolejID As Global.System.Web.UI.WebControls.Label
End Class
