'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebUserControl3

    '''<summary>
    '''lblSemester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemester As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSesi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSesi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltahun As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNomborPusat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomborPusat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKetuaPemeriksa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKetuaPemeriksa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMataPelajaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMataPelajaran As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoPemeriksa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoPemeriksa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoKp10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoKp10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPengesahanOleh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPengesahanOleh1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNama1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNama1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikh1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDisemakOleh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisemakOleh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNama2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNama2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikh2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikh2 As Global.System.Web.UI.WebControls.Label
End Class
