'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class slip_view

    '''<summary>
    '''lblNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNama As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAngkaGiliran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAngkaGiliran As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKluster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKluster As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKursus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKursus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSemester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemester As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTahun As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodI_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodI_M As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblI_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblI_M As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSemester2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemester2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTahun2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTahun2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodI_M2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodI_M2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblI_M2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblI_M2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmodul11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmodul11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSemester3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemester3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTahun3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTahun3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSemester4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemester4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTahun4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTahun4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul32 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul32 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul33 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul33 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKodModul34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodModul34 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModul34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModul34 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJJKA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJJKA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJJKV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJJKV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPK As Global.System.Web.UI.WebControls.Label
End Class
