'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bmsetara_ulang

    '''<summary>
    '''bmsetara_pelajar_ulang_create1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bmsetara_pelajar_ulang_create1 As Global.apkv_v2_user.bmsetara_pelajar_ulang_create
End Class
