'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class slip_pernyataan_keputusan

    '''<summary>
    '''pentaksiran_sijil_vokasional1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pentaksiran_sijil_vokasional1 As Global.apkv_v2_user.pentaksiran_sijil_vokasional
End Class
